### ISSUE TITLE
Calendar View Modules

### ISSUE THREAD

**Issue by justinepocock** [localgovdrupal/localgov_events#140]
To investigate the best modules for a calendar view

### Calendar View https://www.drupal.org/project/calendar_view 

I made a start looking at Calendar View module but I couldn't get it to play nicely with the date fields that we have in LGD. The settings page of the Page Style didn't enable event with localgov_event_date added as a field (without the Occurrences relationship) 

I'm also think this won't work with the search API way of doing events we want to? 

![Image](https://github.com/localgovdrupal/localgov_events/assets/638213/d9b45d74-2268-4296-9218-58bb2b6b62ce)

![Image](https://github.com/localgovdrupal/localgov_events/assets/638213/15e1208f-d361-4251-ae68-bcaac7d1d1f3)

### FullCalendar View  https://www.drupal.org/project/fullcalendar_view 

There's a module for this but @ekes said "I've used fullcalendar.js to do this on a couple of 'intranet-ish' sites. Implemented the js directly myself on a view style, not using a Drupal module. It's overkill but worked." Trying the module now. 

Took some tweaking and a patch to do this for normal views - but module is nice - fullcalendar.js seems to have all the options we need. Probably easier to do it 'The ekes Way' when we add directory channels into the mix. 

"Full calendar view not supporting Date_recur field": "https://www.drupal.org/files/issues/2023-12-14/3408497-date-recur-compatibility.patch"

![Image](https://github.com/localgovdrupal/localgov_events/assets/638213/cd09dc5c-eeca-49a3-ba5c-ecae022f291e)

**Comment by finnlewis** [comment]
Which councils want / need calendar views?

- Wirral (Jamie)
- Hammersmith (Ryan)
- BHCC (Maybe) 
- Newcastle (Jordan / Chris)

**Comment by joachim-n** [comment]
Bit of a showstopper with fullcalendar_view: it doesn't work with SearchAPI indexes: https://www.drupal.org/project/fullcalendar_view/issues/3488112

UPDATE: I've been pointed towards fullcalendar_solr module instead.

**Comment by joachim-n** [comment]
fullcalendar_solr doesn't work with that we have either...

**Comment by ekes** [comment]
I've only ever used fullcalender js directly never used the module. Fed it json output from views iirc.

**Comment by joachim-n** [comment]
So did you change the view to output JSON in the page, and then have the JS use that? Or was it JSON from an endpoint?

**Comment by ekes** [comment]
Think I've done both over the years. My JS hasn't been good enough with the json endpoint version to load it early enough to stop there being a delay in displaying the calendar though.

**Comment by joachim-n** [comment]
Unless there's anything horrible I've not seen yet, I think [calendar_view](https://www.drupal.org/project/calendar_view) could work if we make a custom style plugin which inherits from the style plugin in that module. It looks like we can override a few methods to convince it that our SearchAPI date field is a date field that it likes.

**Comment by joachim-n** [comment]
Ok yes, with minimal hacking I have [calendar_view](https://www.drupal.org/project/calendar_view) working.

**Comment by willguv** [comment]
Closing as we have a calendar view working
