### ISSUE TITLE
Select location = not working

### ISSUE THREAD

**Issue by JonathanDHolden** [localgovdrupal/localgov_events#149]
On the Select Location modal, there are some strange things when we "Create new address"

1. There's what appears to be a Form label "Address*" which has no Input. 

![Screenshot 2024-07-17 07 38 45](https://github.com/user-attachments/assets/11fd12e8-376f-4457-ab66-1e5c32d4dbcd)

2. There's supposed to be a "Populate from address field' button" but it doesn't exist. 

![Screenshot 2024-07-17 07 38 30](https://github.com/user-attachments/assets/ff32d280-3499-4e59-b0c1-5a80492dee2c)

3. When scrolling through the modal (why do we need a modal, why not build into the page? ) you end up with mouse over the map, and zooming the map, and you may not realise there are other sections below the map. 
4. The location map doesn't show anything other than sea
5. The label "Accessibility" could better say "Access information for this location"  (front loaded "access", not confused with WCAG). There should be some padding above the label too. 
6. The submit button says "Save address" but it should say "Create Address"

**Comment by andybroomfield** [comment]
Do you have a geocoder installed?
Some of these issues might be solvable under structure -> geo types -> address -> manage form display. 
I think some are upstream bugs, the `Populate from address field` is not even present as a hidden field.

**Comment by andybroomfield** [comment]
@JonathanDHolden Under structure -> content types -> event -> manage form display you could try changing the widget used from an entitiy browser to an inline entity form. Though I seem to rember there are sme bugs here.

<img width="880" alt="Screenshot 2024-07-17 at 5 26 53 PM" src="https://github.com/user-attachments/assets/0f1aa681-585f-4104-82b6-19f1c302c6d3">

**Comment by JonathanDHolden** [comment]
Solution:
Under structure -> content types -> event -> manage form display Set Address Field to OpenStreetMap (Nominatum)
![image](https://github.com/user-attachments/assets/03109fae-df0b-4b65-9e94-b0b236bd960b)
