### ISSUE TITLE
Automatic update of Ends On date when the Starts On date is input

### ISSUE THREAD

**Issue by JonathanDHolden** [localgovdrupal/localgov_events#150]
When you add a Starts on date eg 15/01/2025 , the ends on should update to the same date. 
My guess is that most events are only on one day, but changing the end date available. 
Saving without changing the End on date leads to an error (white screen with error message). It would be better to have an error on the Ends on field. 

The filled in time is the time on the computer clock, which at 10:36 leads to extra clicks to add the Event time. It might be better to have a default start time of 09:00:00. There is never any relation between the start time of the event and the time the user happens to be adding the event. Also this would give less messing about as almost all events start on the hour. Having to edit minutes is just silly.

**Comment by andybroomfield** [comment]
Do you mean like this... (re: auto set end date).


https://github.com/user-attachments/assets/ce5aac6f-d8b2-427f-855a-e160f8cf4e32

This can be done by changing the date widget to sierra under stucture -> content types -> event -> manage form display.

I think we are going to need to have our own widget at some point, our main pain point is removing seconds from the time.

*Edited to add the correct video*
