### ISSUE TITLE
Patch no longer needed

### ISSUE THREAD

**Issue by benlamptey** [localgovdrupal/localgov_events#69]
Hey there,

Patch is no longer needed for the data_recur module

Could this be looked at asap?, I can verify that the code in the patch is now within the module itself.
Sadly blocking a deployment we need to push up

```
  Cannot apply patch Fix schema #3173876 (https://www.drupal.org/files/issues/2020-10-02/views-field-date-recur-date-schema-3173876-5.patch)!
```

I tried creating a PR to make life easier but I think I need some permission or something. (First time creating a pr to an outside repo - forgive me if there's genuinely a way to do this and i missed it!)

**Comment by andybroomfield** [comment]
Thanks for reporting @benlamptey, do you want to give PR #70 a try?

**Comment by benlamptey** [comment]
amazing! all good from me @andybroomfield

**Comment by willguv** [comment]
Cheers @andybroomfield!

And thanks for letting us know about this @benlamptey
