### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_events#91]
Issue to track any changes needed to support Drupal 10

**Comment by ekes** [comment]
Date Recur Modular has a new D10 only version 3.1.0-rc1 

https://www.drupal.org/project/date_recur_modular/issues/3296930
https://www.drupal.org/project/date_recur_modular/issues/3301519

**Comment by finnlewis** [comment]
looks like it also still supports 9.5+ : 
https://git.drupalcode.org/project/date_recur_modular/-/blob/3.1.x/date_recur_modular.info.yml#L4

**Comment by stephen-cox** [comment]
Closing as we have D10 support working
