### ISSUE TITLE
Show repeating events as one instance in the event list

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_events#99]
Reported by @Grenalich. Possibly a problem for Waltham Forest too? Copying @Boosmith

eg on https://www.walthamforest.gov.uk/events

"Henry Infant Feeding Cafe"

![Image](https://github.com/localgovdrupal/localgov_events/assets/708140/1e7de800-735c-4434-b96f-b8b07ccd0193)

**Comment by andybroomfield** [comment]
Isn't the two Henry Infant Feeding Cafe events actully seperate events, as they are in two different locations?
- [Chingford](https://www.walthamforest.gov.uk/events/henry-infant-feeding-cafe-chingford)
- [Walthamstow](https://www.walthamforest.gov.uk/events/henry-infant-feeding-cafe-walthamstow)

**Comment by willguv** [comment]
Sorry, done in haste - I'll find better examples

**Comment by willguv** [comment]
Talking with @LizziCBFC about this. Ideally:

- if a user is searching by week and there's an instance of the event, show it
- if looking at the whole list, show it once

Lizzie, please post some examples - thanks!

**Comment by willguv** [comment]
Trying to change this is problematic

- if user is scrolling the list/ filtering they'll want to see the event against a particular date
- adding all dates to initial entry would make a very long entry

@finnlewis optional config to show event once, edit per event? 

We think this is a problem with certain events flooding the screen. @RyanFH257 please post the example you found

**Comment by willguv** [comment]
Closing as it may be fixed with events v2, and we can raise again then
